✨ Some opa utilities

diff --git a/examples/offline/build-offline-bundle b/examples/offline/build-offline-bundle
--- a/examples/offline/build-offline-bundle
+++ b/examples/offline/build-offline-bundle
@@ -179,6 +179,10 @@ if ! helm pull --repo https://charts.bitnami.com/bitnami --version 10.16.2 --des
   monolog ERROR "Unable to helm pull postgresql"
   exit 1
 fi
+if ! helm pull --repo https://helm.twun.io --version 2.1.0 --destination "${OUT_DIR}/charts" docker-registry; then
+  monolog ERROR "Unable to helm pull twuni/docker-registry"
+  exit 1
+fi
 
 # First party helm charts
 for x in attributes entitlement-store entitlement-pdp entitlements kas keycloak-bootstrap; do
