Add requests from deployment team

diff --git a/examples/offline/build-offline-bundle b/examples/offline/build-offline-bundle
--- a/examples/offline/build-offline-bundle
+++ b/examples/offline/build-offline-bundle
@@ -148,6 +148,11 @@ if [[ ! $no_third_party ]]; then
   # Update URI: https://hub.docker.com/r/bitnami/postgresql/tags
   save-image bitnami/postgresql 12.8.0 third-party-image-postgresql
   # Keycloak: Since we are bulding a custom image, we don't include that in thirdparty but in primary bundle
+
+  save-image maven 3.6-jdk-11 third-party-image-maven
+  if ! save-image virtru/openfire 0.1 third-party-image-openfire; then
+    monolog WARN "Unable to pull openfire. Have you logged in as a virtru user to docker.io?"
+  fi
 fi
 
 # Third party helm charts
