s/zip/tgz/ eetc

diff --git a/examples/offline/build-offline-bundle b/examples/offline/build-offline-bundle
--- a/examples/offline/build-offline-bundle
+++ b/examples/offline/build-offline-bundle
@@ -271,9 +271,9 @@ pip-latest opentdf
 
 # BUNDLE THAT STUFF UP
 if [[ ! $no_zip ]]; then
-  fname="offline-bundle-${suffix}.zip"
-  if ! (cd "${OUTPUT_DIRECTORY}" && zip -r "${fname}" bundle); then
-    monolog ERROR "Failed to export as zip file"
+  fname="offline-bundle-${suffix}.tgz"
+  if ! (cd "${OUTPUT_DIRECTORY}" && tar -czf "${fname}" bundle); then
+    monolog ERROR "Failed to export as tgz file"
     exit 1
   fi
   monolog DEBUG "Saved stuff as ${OUTPUT_DIRECTORY}/${fname}"
diff --git a/examples/offline/test-offline-bundle b/examples/offline/test-offline-bundle
--- a/examples/offline/test-offline-bundle
+++ b/examples/offline/test-offline-bundle
@@ -15,8 +15,8 @@ monolog TRACE "Running [$0${1+ }$*]"
 export LOCAL_TOOL
 
 if [[ $1 ]]; then
-  if ! unzip "$1"; then
-    monolog ERROR "Unable to unzip bundle [${1}]"
+  if ! tar -xzvf "$1"; then
+    monolog ERROR "Unable to untar bundle [${1}]"
     exit 1
   fi
 
@@ -25,7 +25,7 @@ if [[ $1 ]]; then
     exit 1
   fi
 else
-  # Validating a local run of build-offline-bundle; no need to unzip
+  # Validating a local run of build-offline-bundle; no need to untar
   if ! cd "$EXPORT_ROOT"; then
     monolog ERROR "Unable to find export root [${EXPORT_ROOT}] from APP_DIR=[${APP_DIR}]"
     exit 1
